version: "3.8"

services:
  server:
    build: ./server
    container_name: ai-chatbot-server
    restart: always
    env_file: ./server/.env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      args:
        VITE_API_URL: "http://server:4000"
    container_name: ai-chatbot-client
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - server

  mongo:
    image: mongo:7
    container_name: ai-chatbot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
